/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PANTALLAS;

import CLASES.ControlSemanalLlantas;
import CLASES.ControlSemanalPresionesLlantas;
import CLASES.DataUser;
import CLASES.ModuloMySQL;
import CLASES.ValoresEstaticos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Esteban
 */
public final class Control_PresionesLlantasSemanal extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_Ingreso
     */
    public Control_PresionesLlantasSemanal() {
        
        initComponents();
        isActualizacion=false;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();   
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);
        getListLugares();
        getBuses();
        jLabelTitulo.setText(jLabelTitulo.getText()+" "+ValoresEstaticos.getNombreEmpresa().toUpperCase());
        setCheckBox3Eje();
         Image i=new ImageIcon("C://SCI//SCI.png").getImage();
        this.setIconImage(i);
        jLabelVersion.setText("Sistema Control de Indicadores Version: "+ValoresEstaticos.version_sci+"  Usuario Actual: "+DataUser.username);
        //getListConductores();
        //ValoresEstaticos.espere.setVisible(false);
    }
    public Control_PresionesLlantasSemanal(int con) {
        try {
            initComponents();
            getBuses();
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            int w = this.getSize().width;
            int h = this.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;
            this.setLocation(x, y);
            getListLugares();
            jLabelTitulo.setText(jLabelTitulo.getText()+" "+ValoresEstaticos.getNombreEmpresa().toUpperCase());
            setCheckBox3Eje();
            Image i=new ImageIcon("C://SCI//SCI.png").getImage();
            this.setIconImage(i);
            jLabelVersion.setText("Sistema Control de Indicadores Version: "+ValoresEstaticos.version_sci+"  Usuario Actual: "+DataUser.username);
            ResultSet rs=modulo.Listar("Select * from ControlSemanalPresionesLlantas where Consecutivo='"+con+"' and IdEmpresa='"+ValoresEstaticos.getIdEmpresa()+"'");
            rs.first();
            SimpleDateFormat sf=new SimpleDateFormat("dd-MM-yyyy");            
            jTxtFecha.setText(sf.format(rs.getDate("Fecha")));
            jComboBoxBuses.setSelectedItem(rs.getString("Unidad"));
            unidad=Integer.parseInt(rs.getString("Unidad"));
            
            jTxtArticuladaDerecha.setText(rs.getString("PresionTAD"));
            jTxtArticuladaIzquierda.setText(rs.getString("PresionTAI"));
            jTxtDelanteraDerecha.setText(rs.getString("PresionDD"));
            jTxtDelanteraIzquierda.setText(rs.getString("PresionDI"));
            jTxtResponsable.setText(rs.getString("Responsable"));
            jTxtTraseraDerechaExt.setText(rs.getString("PresionTDE"));
            jTxtTraseraDerechaInt.setText(rs.getString("PresionTDI"));
            jTxtTraseraIzquierdaExt.setText(rs.getString("PresionTIE"));
            jTxtTraseraIzquierdaInt.setText(rs.getString("PresionTII"));
            idPlantel=rs.getInt("Predio");
            jComboBoxLugares.setSelectedItem(rs.getObject("Predio"));
            isActualizacion=true;
            jButton1.setText("Actualizar");
            consecutivo=con;
            //ValoresEstaticos.espere.setVisible(false);
            //getListConductores();
        } catch (SQLException ex) {
            //ValoresEstaticos.espere.setVisible(false);
            Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(Level.SEVERE, null, ex);
            java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                new ListadoLlantasSemanal().setVisible(true);
            }
            });
            this.dispose();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtTraseraIzquierdaInt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtTraseraIzquierdaExt = new javax.swing.JTextField();
        jTxtResponsable = new javax.swing.JTextField();
        jTxtDelanteraDerecha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTxtDelanteraIzquierda = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTxtFecha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTxtArticuladaIzquierda = new javax.swing.JTextField();
        jTxtArticuladaDerecha = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtTraseraDerechaInt = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTxtTraseraDerechaExt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jCheckBoxHabilitar3eje = new javax.swing.JCheckBox();
        jButtonListado = new javax.swing.JButton();
        jComboBoxLugares = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxBuses = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButtonControlMovimientos = new javax.swing.JButton();
        jButtonIngrLlantasNuevas = new javax.swing.JButton();
        jButtonControlSemanal = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonControlMovimientos1 = new javax.swing.JButton();
        jButtonControlSemanal1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonReporteria = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelVersion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Control de Indicadores.");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), new java.awt.Color(0, 102, 153)));

        jLabel39.setBackground(new java.awt.Color(0, 0, 0));
        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("CONTROL SEMANAL PRESIONES DE LLANTAS");
        jLabel39.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(188, 74, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Responsable");
        jLabel3.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(188, 74, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Unidad");
        jLabel2.setOpaque(true);

        jTxtTraseraIzquierdaInt.setBackground(new java.awt.Color(102, 102, 102));
        jTxtTraseraIzquierdaInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtTraseraIzquierdaInt.setForeground(new java.awt.Color(255, 255, 255));
        jTxtTraseraIzquierdaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTraseraIzquierdaInt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtTraseraIzquierdaInt.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtTraseraIzquierdaInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtTraseraIzquierdaIntFocusLost(evt);
            }
        });
        jTxtTraseraIzquierdaInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtTraseraIzquierdaIntKeyPressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(188, 74, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Delantera Derecha");
        jLabel8.setOpaque(true);

        jTxtTraseraIzquierdaExt.setBackground(new java.awt.Color(102, 102, 102));
        jTxtTraseraIzquierdaExt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtTraseraIzquierdaExt.setForeground(new java.awt.Color(255, 255, 255));
        jTxtTraseraIzquierdaExt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTraseraIzquierdaExt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtTraseraIzquierdaExt.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtTraseraIzquierdaExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtTraseraIzquierdaExtFocusLost(evt);
            }
        });
        jTxtTraseraIzquierdaExt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtTraseraIzquierdaExtKeyPressed(evt);
            }
        });

        jTxtResponsable.setBackground(new java.awt.Color(102, 102, 102));
        jTxtResponsable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtResponsable.setForeground(new java.awt.Color(255, 255, 255));
        jTxtResponsable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtResponsable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtResponsable.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtResponsable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtResponsableKeyPressed(evt);
            }
        });

        jTxtDelanteraDerecha.setBackground(new java.awt.Color(102, 102, 102));
        jTxtDelanteraDerecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtDelanteraDerecha.setForeground(new java.awt.Color(255, 255, 255));
        jTxtDelanteraDerecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtDelanteraDerecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtDelanteraDerecha.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtDelanteraDerecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtDelanteraDerechaFocusLost(evt);
            }
        });
        jTxtDelanteraDerecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtDelanteraDerechaKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/save_1.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTxtDelanteraIzquierda.setBackground(new java.awt.Color(102, 102, 102));
        jTxtDelanteraIzquierda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtDelanteraIzquierda.setForeground(new java.awt.Color(255, 255, 255));
        jTxtDelanteraIzquierda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtDelanteraIzquierda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtDelanteraIzquierda.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtDelanteraIzquierda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtDelanteraIzquierdaFocusLost(evt);
            }
        });
        jTxtDelanteraIzquierda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtDelanteraIzquierdaKeyPressed(evt);
            }
        });

        jLabel38.setBackground(new java.awt.Color(188, 74, 0));
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Delantera Izquierda");
        jLabel38.setOpaque(true);

        jTxtFecha.setBackground(new java.awt.Color(102, 102, 102));
        jTxtFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtFecha.setForeground(new java.awt.Color(255, 255, 255));
        jTxtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFechaMouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(188, 74, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("FECHA");
        jLabel15.setOpaque(true);

        jLabel40.setBackground(new java.awt.Color(0, 0, 0));
        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("INFORMACION LLANTAS DELANTERAS");
        jLabel40.setOpaque(true);

        jLabel41.setBackground(new java.awt.Color(0, 0, 0));
        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("INFORMACION LLANTAS TRASERAS");
        jLabel41.setOpaque(true);

        jLabel42.setBackground(new java.awt.Color(188, 74, 0));
        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Trasera Izq. Interna");
        jLabel42.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(188, 74, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Trasera Izq. Externa");
        jLabel14.setOpaque(true);

        jLabel43.setBackground(new java.awt.Color(0, 0, 0));
        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("INFORMACION LLANTAS EJE ARTICULADO");
        jLabel43.setOpaque(true);

        jLabel44.setBackground(new java.awt.Color(188, 74, 0));
        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Articulada Izquierda");
        jLabel44.setOpaque(true);

        jTxtArticuladaIzquierda.setBackground(new java.awt.Color(102, 102, 102));
        jTxtArticuladaIzquierda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtArticuladaIzquierda.setForeground(new java.awt.Color(255, 255, 255));
        jTxtArticuladaIzquierda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtArticuladaIzquierda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtArticuladaIzquierda.setEnabled(false);
        jTxtArticuladaIzquierda.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtArticuladaIzquierda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtArticuladaIzquierdaFocusLost(evt);
            }
        });

        jTxtArticuladaDerecha.setBackground(new java.awt.Color(102, 102, 102));
        jTxtArticuladaDerecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtArticuladaDerecha.setForeground(new java.awt.Color(255, 255, 255));
        jTxtArticuladaDerecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtArticuladaDerecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtArticuladaDerecha.setEnabled(false);
        jTxtArticuladaDerecha.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtArticuladaDerecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtArticuladaDerechaFocusLost(evt);
            }
        });
        jTxtArticuladaDerecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtArticuladaDerechaKeyPressed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(188, 74, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Articulada Derecha");
        jLabel16.setOpaque(true);

        jTxtTraseraDerechaInt.setBackground(new java.awt.Color(102, 102, 102));
        jTxtTraseraDerechaInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtTraseraDerechaInt.setForeground(new java.awt.Color(255, 255, 255));
        jTxtTraseraDerechaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTraseraDerechaInt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtTraseraDerechaInt.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtTraseraDerechaInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtTraseraDerechaIntFocusLost(evt);
            }
        });
        jTxtTraseraDerechaInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtTraseraDerechaIntKeyPressed(evt);
            }
        });

        jLabel45.setBackground(new java.awt.Color(188, 74, 0));
        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Trasera Der. Interna");
        jLabel45.setOpaque(true);

        jTxtTraseraDerechaExt.setBackground(new java.awt.Color(102, 102, 102));
        jTxtTraseraDerechaExt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtTraseraDerechaExt.setForeground(new java.awt.Color(255, 255, 255));
        jTxtTraseraDerechaExt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTraseraDerechaExt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTxtTraseraDerechaExt.setSelectionColor(new java.awt.Color(0, 51, 102));
        jTxtTraseraDerechaExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtTraseraDerechaExtFocusLost(evt);
            }
        });
        jTxtTraseraDerechaExt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtTraseraDerechaExtKeyPressed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(188, 74, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Trasera Der. Externa");
        jLabel17.setOpaque(true);

        jCheckBoxHabilitar3eje.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxHabilitar3eje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBoxHabilitar3eje.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxHabilitar3eje.setText("Habilitar tercer eje");
        jCheckBoxHabilitar3eje.setFocusable(false);

        jButtonListado.setBackground(new java.awt.Color(51, 51, 51));
        jButtonListado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonListado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/list.png"))); // NOI18N
        jButtonListado.setText("VER LISTADO");
        jButtonListado.setBorder(null);
        jButtonListado.setFocusable(false);
        jButtonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoActionPerformed(evt);
            }
        });

        jComboBoxLugares.setBackground(new java.awt.Color(102, 102, 102));
        jComboBoxLugares.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxLugares.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(188, 74, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Predio");
        jLabel4.setOpaque(true);

        jComboBoxBuses.setBackground(new java.awt.Color(102, 102, 102));
        jComboBoxBuses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxBuses.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTxtFecha, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jComboBoxBuses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtResponsable)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxLugares, 0, 154, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addComponent(jButtonListado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(359, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxtDelanteraIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtDelanteraDerecha)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtTraseraIzquierdaInt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtTraseraIzquierdaExt)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtTraseraDerechaInt))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtTraseraDerechaExt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtArticuladaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtArticuladaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxHabilitar3eje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel8)
                    .addComponent(jLabel42)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDelanteraIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDelanteraDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTraseraIzquierdaInt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTraseraIzquierdaExt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtArticuladaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtArticuladaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtTraseraDerechaInt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTraseraDerechaExt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jCheckBoxHabilitar3eje)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jButtonControlMovimientos.setBackground(new java.awt.Color(0, 0, 0));
        jButtonControlMovimientos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonControlMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonControlMovimientos.setText("Control de Movimientos");
        jButtonControlMovimientos.setFocusable(false);
        jButtonControlMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlMovimientosActionPerformed(evt);
            }
        });

        jButtonIngrLlantasNuevas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonIngrLlantasNuevas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIngrLlantasNuevas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngrLlantasNuevas.setText("Ingreso de Llantas Nuevas");
        jButtonIngrLlantasNuevas.setFocusable(false);
        jButtonIngrLlantasNuevas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngrLlantasNuevasActionPerformed(evt);
            }
        });

        jButtonControlSemanal.setBackground(new java.awt.Color(0, 0, 0));
        jButtonControlSemanal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonControlSemanal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonControlSemanal.setText("Control Semanal Profundidades");
        jButtonControlSemanal.setFocusable(false);
        jButtonControlSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlSemanalActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SELECCIONE UNA FUNCION");
        jLabel12.setOpaque(true);

        jButtonControlMovimientos1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonControlMovimientos1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonControlMovimientos1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonControlMovimientos1.setText("Control de Reencauches");
        jButtonControlMovimientos1.setFocusable(false);
        jButtonControlMovimientos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlMovimientos1ActionPerformed(evt);
            }
        });

        jButtonControlSemanal1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlSemanal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonControlSemanal1.setText("Control Semanal Presiones");
        jButtonControlSemanal1.setFocusable(false);
        jButtonControlSemanal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlSemanal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonControlMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIngrLlantasNuevas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonControlSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonControlSemanal1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonControlMovimientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonControlMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIngrLlantasNuevas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonControlSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonControlMovimientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonControlSemanal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabelTitulo.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("INGRESO DE DATOS AL SISTEMA SCI");
        jLabelTitulo.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/SCI.png"))); // NOI18N
        jLabel9.setOpaque(true);

        jButtonReporteria.setBackground(new java.awt.Color(51, 51, 51));
        jButtonReporteria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReporteria.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReporteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/reportes.png"))); // NOI18N
        jButtonReporteria.setText("Reporteria");
        jButtonReporteria.setBorder(null);
        jButtonReporteria.setFocusable(false);
        jButtonReporteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReporteria, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonReporteria, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control Semanal Presiones de Llantas");

        jLabelVersion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelVersion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersion.setText("Version.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVersion)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SELECCIONE UN TIPO DE CONTROL");
        jLabel13.setOpaque(true);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 51));
        jButton2.setText("Ingresos Diarios");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 102));
        jButton4.setText("Control de Llantas");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 153, 51));
        jButton5.setText("Control de Aceites");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 153, 51));
        jButton6.setText("SALIR");
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 153, 51));
        jButton7.setText("Parametros de Empresa");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 153, 51));
        jButton8.setText("Control de Baterias");
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 153, 51));
        jButton9.setText("Ordenes de Trabajo");
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (isActualizacion){
                
                SimpleDateFormat sf=new SimpleDateFormat("dd-MM-yyyy");
                Date fecha=sf.parse(jTxtFecha.getText());
                Calendar c=Calendar.getInstance();
                
                if (fecha.getTime()==c.getTimeInMillis()||fecha.before(new Date(c.getTimeInMillis())))
                {
                fechallantaentra=new java.sql.Date(fecha.getTime());
                datos.setFecha(fechallantaentra);
                } 
            
                else {
                JOptionPane.showMessageDialog(rootPane, "Fecha digitada mayor a la fecha actual, no se puede guardar el registro. Revise la fecha digitada y la fecha de la computadora");
                return;
                }
                if (jTxtDelanteraDerecha.getText().length()>0){
                datos.setPresionDD(Integer.parseInt(jTxtDelanteraDerecha.getText()));
                
                }
                else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Delantera Derecha no digitada");
                return;
                }
            
            
            if (jTxtDelanteraIzquierda.getText().length()>0){
                datos.setPresionDI(Integer.parseInt(jTxtDelanteraIzquierda.getText()));
                
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Delantera Izquierda no digitada");
                return;
            }
            
            if (jTxtTraseraIzquierdaInt.getText().length()>0){
                datos.setPresionTII(Integer.parseInt(jTxtTraseraIzquierdaInt.getText()));
                
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Izquierda interna no digitada");
                return;
            }
            if (jTxtTraseraIzquierdaExt.getText().length()>0){
                datos.setPresionTIE(Integer.parseInt(jTxtTraseraIzquierdaExt.getText()));
                
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Izquierda Externa no digitada");
                return;
            }
            if (jTxtTraseraDerechaInt.getText().length()>0){
                datos.setPresionTDI(Integer.parseInt(jTxtTraseraDerechaInt.getText()));
             
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Derecha Interna no digitada");
                return;
            }
            if (jTxtTraseraDerechaExt.getText().length()>0){
                JOptionPane.showMessageDialog(rootPane, Integer.parseInt(jTxtTraseraDerechaExt.getText()));
                datos.setPresionTDE(Integer.parseInt(jTxtTraseraDerechaExt.getText()));
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Derecha Externa no digitada");
                return;
            }
            if (jCheckBoxHabilitar3eje.isSelected()){
            if (jTxtArticuladaIzquierda.getText().length()>0){
                datos.setPresionTAI(Integer.parseInt(jTxtArticuladaIzquierda.getText()));
            }
            if (jTxtArticuladaDerecha.getText().length()>0){
                datos.setPresionTAD(Integer.parseInt(jTxtArticuladaIzquierda.getText()));
            }
            }
            datos.setUnidad(unidad);
            datos.setResponsable(jTxtResponsable.getText());
            datos.setPredio(idPlantel);
            if (datos.updateDataMySql(consecutivo)){
                    isActualizacion=false;
                    consecutivo=0;
                    jButton1.setText("Guardar");
                    clearData();
                    jComboBoxBuses.grabFocus();
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "No se pudo guardar los cambios en el registro de la unidad="+unidad);
                }
             
            }
            else{
            SimpleDateFormat sf=new SimpleDateFormat("dd-MM-yyyy");
            Date fecha=sf.parse(jTxtFecha.getText());
            Calendar c=Calendar.getInstance();
            if (testUnit(fecha,unidad)==false){
            if (fecha.getTime()==c.getTimeInMillis()||fecha.before(new Date(c.getTimeInMillis())))
            {
                fechallantaentra=new java.sql.Date(fecha.getTime());
                datos.setFecha(fechallantaentra);
            } 
            
            else {
                JOptionPane.showMessageDialog(rootPane, "Fecha digitada mayor a la fecha actual, no se puede guardar el registro. Revise la fecha digitada y la fecha de la computadora");
                return;
            }
            if (jTxtDelanteraDerecha.getText().length()>0){
                datos.setPresionDD(Integer.parseInt(jTxtDelanteraDerecha.getText()));
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Delantera Derecha no digitada");
                return;
            }
            
            
            if (jTxtDelanteraIzquierda.getText().length()>0){
                datos.setPresionDI(Integer.parseInt(jTxtDelanteraIzquierda.getText()));
                
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Delantera Izquierda no digitada");
                return;
            }
            
            if (jTxtTraseraIzquierdaInt.getText().length()>0){
                datos.setPresionTII(Integer.parseInt(jTxtTraseraIzquierdaInt.getText()));
                
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Izquierda interna no digitada");
                return;
            }
            if (jTxtTraseraIzquierdaExt.getText().length()>0){
                datos.setPresionTIE(Integer.parseInt(jTxtTraseraIzquierdaExt.getText()));
                
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Izquierda Externa no digitada");
                return;
            }
            if (jTxtTraseraDerechaInt.getText().length()>0){
                datos.setPresionTDI(Integer.parseInt(jTxtTraseraDerechaInt.getText()));
             
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Derecha Interna no digitada");
                return;
            }
            if (jTxtTraseraDerechaExt.getText().length()>0){
                datos.setPresionTDE(Integer.parseInt(jTxtTraseraDerechaExt.getText()));
             
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Profundidad Llanta Trasera Derecha Externa no digitada");
                return;
            }
            if (jCheckBoxHabilitar3eje.isSelected()){
            if (jTxtArticuladaIzquierda.getText().length()>0){
                datos.setPresionTAI(Integer.parseInt(jTxtArticuladaIzquierda.getText()));
            }
            if (jTxtArticuladaDerecha.getText().length()>0){
                datos.setPresionTAD(Integer.parseInt(jTxtArticuladaDerecha.getText()));
            }
            }
            
            datos.setUnidad(unidad);
            datos.setResponsable(jTxtResponsable.getText());
            datos.setPredio(idPlantel);
                if (datos.saveDataMySql())
                {
                    clearData();
                    jComboBoxBuses.grabFocus();
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Unidad "+unidad+" ya tiene registros guardados el "+jTxtFecha.getText());
                    jComboBoxBuses.grabFocus();
                }
            } } 
        } catch (ParseException ex) {
            Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean testUnit(Date date, int unidad){
        java.sql.Date da=new java.sql.Date(date.getTime());
        String comando="Select * from ControlSemanalLlantas Where Fecha='"+da+"' and Unidad='"+unidad+"' and IdEmpresa='"+ValoresEstaticos.getIdEmpresa()+"'";
        //JOptionPane.showMessageDialog(rootPane, comando);
        ResultSet rs=modulo.Listar(comando);
        if (rs!=null){
            try {
                return rs.first();
            } catch (SQLException ex) {
                Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
        else{
        return false;
        }
        
    }
    public void getBuses(){
       // String s="Select Unidad from UnidadesxEmpresa where IdEmpresa='"+ValoresEstaticos.getIdEmpresa()+"'";
        final ResultSet rs=modulo.Listar("Select Unidad from UnidadesxEmpresa where IdEmpresa='"+ValoresEstaticos.getIdEmpresa()+"' and Estado='1' ORDER BY Unidad");
        // Logger.getLogger(Control_Aceites.class.getName()).log(Level.SEVERE, s);
        if (rs!=null){
            try {
                while(rs.next()){
                 jComboBoxBuses.addItem(rs.getString("Unidad"));
                  
                }
                jComboBoxBuses.addItemListener(new ItemListener() {

                    @Override
                    public void itemStateChanged(ItemEvent e) {
                        try {
                            int index=jComboBoxBuses.getSelectedIndex()+1;
                            rs.absolute(index);
                            unidad=rs.getInt("Unidad");
                            //JOptionPane.showMessageDialog(rootPane, idPlantel);
                        } catch (SQLException ex) {
                            Logger.getLogger(Control_Aceites.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(rootPane, "ERROR!!!! No se pudo comunicar con el servidor. Por favor verifique que tiene conexion a internet e intente nuevamente "+ex.getMessage());
                        }
                       
                    }
                });
                rs.first();
                unidad=rs.getInt("Unidad");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "ERROR!!!! No se pudo comunicar con el servidor. Por favor verifique que tiene conexion a internet e intente nuevamente "+ex.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "ERROR!!!! No se pudo comunicar con el servidor. Por favor verifique que tiene conexion a internet e intente nuevamente");
        }
    }
    
    public void getListLugares(){
        final ResultSet rs=modulo.Listar("Select * from Planteles_Empresa where IdEmpresa='"+ValoresEstaticos.getIdEmpresa()+"'");
        if (rs!=null){
            try {
                while(rs.next()){
                 jComboBoxLugares.addItem(rs.getString("Plantel"));
                  
                }
                jComboBoxLugares.addItemListener(new ItemListener() {

                    @Override
                    public void itemStateChanged(ItemEvent e) {
                        try {
                            int index=jComboBoxLugares.getSelectedIndex()+1;
                            rs.absolute(index);
                            idPlantel=rs.getInt("IdPlantel");
                            //JOptionPane.showMessageDialog(rootPane, idPlantel);
                        } catch (SQLException ex) {
                            Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(rootPane, "ERROR!!!! No se pudo comunicar con el servidor. Por favor verifique que tiene conexion a internet e intente nuevamente "+ex.getMessage());
                        }
                       
                    }
                });
                rs.first();
                idPlantel=rs.getInt("IdPlantel");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "ERROR!!!! No se pudo comunicar con el servidor. Por favor verifique que tiene conexion a internet e intente nuevamente "+ex.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "ERROR!!!! No se pudo comunicar con el servidor. Por favor verifique que tiene conexion a internet e intente nuevamente");
        }
    }
    private void jTxtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFechaMouseClicked
        // TODO add your handling code here:
        this.jTxtFecha.setText(new DatePicker(this).setPickedDate());
    }//GEN-LAST:event_jTxtFechaMouseClicked

    private void jButtonControlMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlMovimientosActionPerformed
        // TODO add your handling code here:
        jButtonIngrLlantasNuevas.setBackground(Color.BLACK);
        jButtonIngrLlantasNuevas.setForeground(Color.WHITE);
        jButtonControlSemanal.setBackground(Color.BLACK);
        jButtonControlSemanal.setForeground(Color.WHITE);
        jButtonControlMovimientos.setBackground(Color.WHITE);
        jButtonControlMovimientos.setForeground(Color.BLACK);
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                new Control_Llantas().setVisible(true);
            }
       });
       this.dispose();
    }//GEN-LAST:event_jButtonControlMovimientosActionPerformed

    private void jButtonIngrLlantasNuevasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngrLlantasNuevasActionPerformed
        // TODO add your handling code here:
       java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                new Ingreso_Llantas_Nuevas().setVisible(true);
            }
       });
       this.dispose();
    }//GEN-LAST:event_jButtonIngrLlantasNuevasActionPerformed

    private void jButtonControlSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlSemanalActionPerformed
        // TODO add your handling code here:
        
         java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                new Control_LlantasSemanal().setVisible(true);
            }
       });
       this.dispose();
    }//GEN-LAST:event_jButtonControlSemanalActionPerformed

    private void jTxtArticuladaDerechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtArticuladaDerechaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtArticuladaDerechaKeyPressed

    private void jButtonReporteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteriaActionPerformed
        // TODO add your handling code here:
        if (DataUser.permitereporteria){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new Reporteria().setVisible(true);
                }
            });
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "El usuario "+DataUser.username+" no tiene permisos para realizar esta función. Consulte al administrator del sistema", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButtonReporteriaActionPerformed

    private void jTxtTraseraDerechaExtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTraseraDerechaExtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtTraseraDerechaExtKeyPressed

    private void jTxtTraseraDerechaIntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTraseraDerechaIntKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtTraseraDerechaIntKeyPressed

    private void jTxtTraseraIzquierdaExtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTraseraIzquierdaExtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtTraseraIzquierdaExtKeyPressed

    private void jTxtTraseraIzquierdaIntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTraseraIzquierdaIntKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtTraseraIzquierdaIntKeyPressed

    private void jTxtDelanteraDerechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDelanteraDerechaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtDelanteraDerechaKeyPressed

    private void jTxtDelanteraIzquierdaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDelanteraIzquierdaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtDelanteraIzquierdaKeyPressed

    private void jTxtResponsableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtResponsableKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTxtResponsableKeyPressed

    private void jButtonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ListadoPresionesLlantasSemanal().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButtonListadoActionPerformed

    private void jButtonControlMovimientos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlMovimientos1ActionPerformed
        // TODO add your handling code here:
          
         java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                new Control_ReencauchesLlantas().setVisible(true);
            }
       });
       this.dispose();
    }//GEN-LAST:event_jButtonControlMovimientos1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (DataUser.permiso_control_ingresos){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new Nuevo_Ingreso().setVisible(true);
                }
            });
            this.dispose();}
        else{
            JOptionPane.showMessageDialog(rootPane, "El usuario "+DataUser.username+" no tiene permisos para realizar esta función. Consulte al administrator del sistema", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (DataUser.permiso_control_aceites){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new Control_Aceites().setVisible(true);
                }
            });
            this.dispose();}
        else{
            JOptionPane.showMessageDialog(rootPane, "El usuario "+DataUser.username+" no tiene permisos para realizar esta función. Consulte al administrator del sistema", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (DataUser.permiso_control_parametros){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new ParametrosEmpresa().setVisible(true);
                }
            });
            this.dispose();}
        else{
            JOptionPane.showMessageDialog(rootPane, "El usuario "+DataUser.username+" no tiene permisos para realizar esta función. Consulte al administrator del sistema", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (DataUser.permiso_control_baterias){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new Control_Baterias().setVisible(true);
                }
            });
            this.dispose();}
        else{
            JOptionPane.showMessageDialog(rootPane, "El usuario "+DataUser.username+" no tiene permisos para realizar esta función. Consulte al administrator del sistema", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (DataUser.permiso_creacion_ordenestrabajo || DataUser.permiso_cierre_ordenestrabajo){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new ListadoOrdenesTrabajo().setVisible(true);
                }
            });
            this.dispose();}
        else{
            JOptionPane.showMessageDialog(rootPane, "El usuario "+DataUser.username+" no tiene permisos para realizar esta función. Consulte al administrator del sistema", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonControlSemanal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlSemanal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonControlSemanal1ActionPerformed

    private void jTxtDelanteraIzquierdaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtDelanteraIzquierdaFocusLost
            try{
            if (jTxtDelanteraIzquierda.getText().length()>0){
                int a=Integer.parseInt(jTxtDelanteraIzquierda.getText());
                if (a<=99 || a>=121){
                    jTxtDelanteraIzquierda.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
            }
            catch (NumberFormatException ex){
            jTxtDelanteraIzquierda.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jTxtDelanteraIzquierdaFocusLost

    private void jTxtDelanteraDerechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtDelanteraDerechaFocusLost
        // TODO add your handling code here:
        try{
          if (jTxtDelanteraDerecha.getText().length()>0){
                int a=Integer.parseInt(jTxtDelanteraDerecha.getText());
                if (a<=99 || a>=121){
                    jTxtDelanteraDerecha.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
        catch (NumberFormatException ex){
            jTxtDelanteraDerecha.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTxtDelanteraDerechaFocusLost

    private void jTxtTraseraIzquierdaIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtTraseraIzquierdaIntFocusLost
        // TODO add your handling code here:
        try{
          if (jTxtTraseraIzquierdaInt.getText().length()>0){
                int a=Integer.parseInt(jTxtTraseraIzquierdaInt.getText());
                if (a<=99 || a>=121){
                    jTxtTraseraIzquierdaInt.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
        catch (NumberFormatException ex){
            jTxtTraseraIzquierdaInt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTxtTraseraIzquierdaIntFocusLost

    private void jTxtTraseraIzquierdaExtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtTraseraIzquierdaExtFocusLost
        // TODO add your handling code here:
        try{
          if (jTxtTraseraIzquierdaExt.getText().length()>0){
                int a=Integer.parseInt(jTxtTraseraIzquierdaExt.getText());
                if (a<=99 || a>=121){
                    jTxtTraseraIzquierdaExt.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
        catch (NumberFormatException ex){
            jTxtTraseraIzquierdaExt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTxtTraseraIzquierdaExtFocusLost

    private void jTxtTraseraDerechaIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtTraseraDerechaIntFocusLost
        // TODO add your handling code here:
        try{
          if (jTxtTraseraDerechaInt.getText().length()>0){
                int a=Integer.parseInt(jTxtTraseraDerechaInt.getText());
                if (a<=99 || a>=121){
                    jTxtTraseraDerechaInt.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
        catch (NumberFormatException ex){
            jTxtTraseraDerechaInt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTxtTraseraDerechaIntFocusLost

    private void jTxtTraseraDerechaExtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtTraseraDerechaExtFocusLost
        // TODO add your handling code here:
        try{
          if (jTxtTraseraDerechaExt.getText().length()>0){
                int a=Integer.parseInt(jTxtTraseraDerechaExt.getText());
                if (a<=99 || a>=121){
                    jTxtTraseraDerechaExt.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
        catch (NumberFormatException ex){
            jTxtTraseraDerechaExt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTxtTraseraDerechaExtFocusLost

    private void jTxtArticuladaIzquierdaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtArticuladaIzquierdaFocusLost
        // TODO add your handling code here:
        try{
          if (jTxtArticuladaIzquierda.getText().length()>0){
                int a=Integer.parseInt(jTxtArticuladaIzquierda.getText());
                if (a<=99 || a>=121){
                    jTxtArticuladaIzquierda.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
        catch (NumberFormatException ex){
            jTxtArticuladaIzquierda.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTxtArticuladaIzquierdaFocusLost

    private void jTxtArticuladaDerechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtArticuladaDerechaFocusLost
        // TODO add your handling code here:
        try{
          if (jTxtArticuladaDerecha.getText().length()>0){
                int a=Integer.parseInt(jTxtArticuladaDerecha.getText());
                if (a<=99 || a>=121){
                    jTxtArticuladaDerecha.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Valor fuera de rango permitido <=100 y >=120", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
        catch (NumberFormatException ex){
            jTxtArticuladaDerecha.setText("");
            JOptionPane.showMessageDialog(rootPane, "Formato no permitido", "Sistema de Control de Indicadores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTxtArticuladaDerechaFocusLost
    public void setCheckBox3Eje(){
        
        jCheckBoxHabilitar3eje.addItemListener(new ItemListener() {
     
            @Override
            public void itemStateChanged(ItemEvent e) {
               
               if (jCheckBoxHabilitar3eje.isSelected()){
                   //JOptionPane.showConfirmDialog(rootPane, "C");
                   jTxtArticuladaDerecha.setEnabled(true);
                   jTxtArticuladaIzquierda.setEnabled(true);
               }
               else{
                   jTxtArticuladaDerecha.setEnabled(false);
                   jTxtArticuladaIzquierda.setEnabled(false);
               }
            }
        });
    }
    public boolean testLlantaNueva(String s){
        String sentencia="select EstadoLlanta, Status from Mantenimiento_IngresoLlantasNuevas where Cod_Llanta='"+s+"' order by Consecutivo DESC limit 1";
        ResultSet rs=modulo.Listar(sentencia);
        if (rs!=null){
            try {
                rs.first();
                tipoinventariollanta=rs.getInt("EstadoLlanta");
                disponibilidadllanta=rs.getInt("Status");
                if (disponibilidadllanta!=3){
                    JOptionPane.showMessageDialog(rootPane, "Llanta esta actualmente no esta disponible");
                    return false;
                }
                return true;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Codigo de Llanta no existe");
                Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
        else{
            JOptionPane.showConfirmDialog(rootPane, "Error de Comunicacion con Servidor SQL. Intente de nuevo");
            return false;
        }
    }
    public void clearData(){
        
        
        jTxtArticuladaDerecha.setText("");
        jTxtArticuladaIzquierda.setText("");
        jTxtDelanteraDerecha.setText("");
        jTxtDelanteraIzquierda.setText("");
        jTxtTraseraDerechaExt.setText("");
        jTxtTraseraDerechaInt.setText("");
        jTxtTraseraIzquierdaExt.setText("");
        jTxtTraseraIzquierdaInt.setText("");
        unidad=0;
        jTxtArticuladaDerecha.setEnabled(false);
        jTxtArticuladaIzquierda.setEnabled(false);
        jCheckBoxHabilitar3eje.setSelected(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control_PresionesLlantasSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control_PresionesLlantasSemanal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonControlMovimientos;
    private javax.swing.JButton jButtonControlMovimientos1;
    private javax.swing.JButton jButtonControlSemanal;
    private javax.swing.JButton jButtonControlSemanal1;
    private javax.swing.JButton jButtonIngrLlantasNuevas;
    private javax.swing.JButton jButtonListado;
    private javax.swing.JButton jButtonReporteria;
    private javax.swing.JCheckBox jCheckBoxHabilitar3eje;
    private javax.swing.JComboBox jComboBoxBuses;
    private javax.swing.JComboBox jComboBoxLugares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVersion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTxtArticuladaDerecha;
    private javax.swing.JTextField jTxtArticuladaIzquierda;
    private javax.swing.JTextField jTxtDelanteraDerecha;
    private javax.swing.JTextField jTxtDelanteraIzquierda;
    private javax.swing.JTextField jTxtFecha;
    private javax.swing.JTextField jTxtResponsable;
    private javax.swing.JTextField jTxtTraseraDerechaExt;
    private javax.swing.JTextField jTxtTraseraDerechaInt;
    private javax.swing.JTextField jTxtTraseraIzquierdaExt;
    private javax.swing.JTextField jTxtTraseraIzquierdaInt;
    // End of variables declaration//GEN-END:variables
    ControlSemanalPresionesLlantas datos=new ControlSemanalPresionesLlantas();
    static ModuloMySQL modulo=new ModuloMySQL();
    static int idDestino;
    static java.sql.Date fechallantasale;
    static int unidadllantaentra;
    static float kmllantasale;
    static int statusllanteentrante=0;
    static java.sql.Date fechallantaentra;
    static String id=ValoresEstaticos.getIdEmpresa()+"#";
    static int tipoinventariollanta;
    static int disponibilidadllanta;
    static boolean isFirstRegister;
    static boolean isActualizacion=false;
    static int consecutivo;
    static int idPlantel;
    static int unidad;
    
}
